name: Build and Release with Nuitka

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Nuitka and dependencies
      run: |
        apt-get update -y && apt-get install patchelf ccache -y
        python -m pip install --upgrade pip
        pip install nuitka ordered-set
        pip install -r requirements.txt

    - name: Compile code with Nuitka
      run: |
        python -m nuitka --follow-imports --standalone --onefile --output-filename=wg-generator generate-config.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }} Build
        path: ./wg-generator
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ runner.os }} Build
        path: wg-generator

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: wg-generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
