name: Build and Release with Nuitka

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Nuitka and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka ordered-set
        pip install -r requirements.txt

    - name: Compile code with Nuitka
      run: |
        python -m nuitka --follow-imports --standalone --onefile --output-filename=wg-generator --output-dir=dist generate-config.py

    - name: Upload artifact for later use
      uses: actions/upload-artifact@v3
      with:
        name: compiled-binary
        path: dist/wg-generator
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: compiled-binary

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/wg-generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
